apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-wasmcode
  namespace: wasmcode
spec:
  acme:
    email: CHANGE_EMAIL
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-secret-prod-wasmcode
    solvers:
      - http01:
          ingress:
            class: nginx